name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App (Follow Redirects)
        run: curl -sSL "https://makans.streamlit.app/"
