name: Keep Makans Awake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y chromium-browser

      - name: Send request using Chromium
        run: chromium-browser --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 https://makans.streamlit.app
